magazine/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from cars.views import index, comments

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', comments),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', index)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from string import digits
from django.db import models
from django.contrib.auth.models import User

class CarCategory(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title

class Car(models.Model):
    title = models.CharField(max_length=32)
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=20, decimal_places=0)
    image = models.ImageField(upload_to='car-images')
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)
    related_car_category = models.ForeignKey(CarCategory, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.TextField()
    related_car = models.ForeignKey(Car, on_delete=models.CASCADE)
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

cars/forms.py
from django.forms import ModelForm
from .models import Car


class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(CarForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

cars/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from cars.forms import CarForm
from .models import Car, Comment


@login_required
def index(request):
    if request.method == "POST":
        form = CarForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
    else:
        form = CarForm()
    cars = Car.objects.filter()
    title = "Anonymous User"
    if request.user.is_authenticated:
        title = f'{request.user.first_name} {request.user.last_name}'
    context = {
        'title': title,
        'cars': cars,
        'form': form
    }
    return render(request, 'index.html', context)

def comments(request):
    instances = Comment.objects.filter(related_car__related_car_category__title='Super Sport')
    context = {
        'comments': instances
    }
    return render(request, 'comments.html', context)

cars/templates/comments.html
{% extends 'layout.html' %}

{% block main %}
<h1>Comments: </h1>
{% for comment in comments %}
    <p>{{comment.content}}</p>
{% endfor %}
{% endblock %}

cars/templates/index.html
{% extends 'layout.html' %}


{% block main %}
    <h1>{{title}}</h1>
    {% if user.is_authenticated %}
        <h1>{{ user.first_name }} {{user.last_name}}</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Submit">
        </form>
    {% else %}
        <a href="">Login</a>
    {% endif %}
    {% for car in cars %}
        {% if car.image %}
            <img src="{{car.image.url}}" width="256px">
        {% endif %}
        <h2>{{car.title}}</h2>
        <p>{{car.description}}</p>
        <p>{{car.related_user.first_name}} {{car.related_user.last_name}}</p>
        <h3>Comments:</h3>
        {% for comment in car.comment_set.all %}
            <p>{{comment.related_user}}: {{comment.content}}</p>
        {% endfor %}
        <hr>
    {% endfor %}
{% endblock %}

cars/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Tutorial</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    {% block main %}

    {% endblock %}
    </div>
</body>
</html>